spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sis_permissao_dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: geprocseplag@2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:@DY4524U2IY4653IID35435423D3FG35}

  jwt:
    token:
      expiration: 12
    refresh-token:
      expiration: 360

server:
  error:
    include-exception: true

cryptography:
  key: ${CRYPTO_KEY:tEw7Dzk6lilZjT7EVvLNPM6G6FskV2LgyWIvaSUSN2sFEZQAF2}

# Configuração do Swagger
springdoc:
  swagger-ui:
    enabled: true
    path: "/documentation"
    display-request-duration: true
    persist-authorization: true
    operationsSorter: method
    tryItOutEnabled: true
    requestSnippetsEnabled: true